#!/bin/sh

# Automatically deploy a web application by pushing updates to a git
# repository.
#
# For information on usage of this hook, please see the README.md that came
# with your installation of giddyup.
# 

set -e

# Consistent sourcing location for hooks deployed in multiple environments.
FUNCS="$(dirname $(readlink -f $0))/functions.sh"
. $FUNCS

REPO="$(dirname $(cd $(dirname "$0"); pwd -P))"
ROOT="$(dirname "${REPO}")"

# Git-specific stuff starts here
get_config() {
	local option="$1"
	
	git config --file "${REPO}/config" --get giddyup.${option} || true
}

if [ "$(get_config debug)" = "true" ]; then
	set -x
fi

init_env

REF="$1"
OLDREV="$2"
NEWREV="$3"

if [ "$REF" != "refs/heads/master" ]; then
	echo "ERROR: Can only push to master" >&2
	exit 1
fi

cd "${RELEASE}"

git --git-dir "${REPO}" archive --format=tar "${NEWREV}" | tar xf -

cd "${ROOT}"

# End git-specific stuff

cycle_release
